#!/usr/bin/env python3
import re
import sys
from subprocess import check_output

commit_msg_filepath = sys.argv[1]

# Figure out which branch we're on
branch = check_output(["git", "symbolic-ref", "--short", "HEAD"], encoding="UTF-8").strip()
JIRA_URL = check_output(["git", "config", "jira.url"], encoding="UTF-8").strip()
if not JIRA_URL:
    print("No Jira URL configured, please run the command 'git config --global jira.url https://myjira.atlassian.net/browse'")
    sys.exit(1)

with open(commit_msg_filepath, "r") as f:
    content = f.readlines()
    JIRA_FROM_BRANCH = re.search(r"([A-Z]+-\d+)", branch).group(0)
    for line in content:
        if f"{JIRA_URL}/{JIRA_FROM_BRANCH}" in line:
            print(f"Jira found in commit message: {line}")
            sys.exit(0)

print(f"Jira not found in commit message appending to the end")
with open(commit_msg_filepath, "a") as f:
    f.write(f"{JIRA_URL}/{JIRA_FROM_BRANCH}")
